import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
import os

# --- CONFIG ---
# Paths to OOF files (Train set predictions)
OOF_FILES = {
    'LGBM': 'Models/oof_lgbm_optuna.csv',
    'XGB': 'Models/oof_xgb_fast.csv',
    'CatBoost': 'Models/oof_cat_fast.csv'
}

# Paths to Submission files (Test set predictions)
# NOTE: These must correspond to the same models as the OOF files!
SUB_FILES = {
    'LGBM': 'submission_optuna.csv',      # Generated by train_optuna.py / manual script
    'XGB': 'submission_xgb_fast.csv',     # Assumed name
    'CatBoost': 'submission_cat_fast.csv' # Assumed name
}

TARGET_COL = 'loan_paid_back'

def load_data():
    print("Loading data...")
    # Load original train data for target
    if os.path.exists('Processed/clean_train.csv'):
        train = pd.read_csv('Processed/clean_train.csv')
    elif os.path.exists('clean_train.csv'):
        train = pd.read_csv('clean_train.csv')
    else:
        raise FileNotFoundError("Could not find clean_train.csv")
        
    # Load OOF predictions
    oofs = {}
    for model_name, path in OOF_FILES.items():
        if os.path.exists(path):
            df = pd.read_csv(path)
            # Check if 'loan_paid_back' exists, otherwise assume it's the second column or named 'pred'
            if TARGET_COL in df.columns:
                oofs[model_name] = df[TARGET_COL]
            else:
                # Fallback: assume single column or similar
                print(f"Warning: '{TARGET_COL}' column not found in {path}. Using last column.")
                oofs[model_name] = df.iloc[:, -1]
        else:
            raise FileNotFoundError(f"Missing OOF file: {path}")

    # Load Test predictions (for submission)
    subs = {}
    test_ids = None
    for model_name, path in SUB_FILES.items():
        if os.path.exists(path):
            df = pd.read_csv(path)
            if test_ids is None and 'id' in df.columns:
                test_ids = df['id']
            
            if TARGET_COL in df.columns:
                subs[model_name] = df[TARGET_COL]
            else:
                print(f"Warning: '{TARGET_COL}' column not found in {path}. Using last column.")
                subs[model_name] = df.iloc[:, -1]
        else:
            print(f"Warning: Missing Submission file: {path}. Cannot generate submission_stacking.csv without it.")
            
    return train, oofs, subs, test_ids

def main():
    train, oofs, subs, test_ids = load_data()
    
    # Prepare Stacking DataFrames
    X_stack_train = pd.DataFrame(oofs)
    y = train[TARGET_COL]
    
    # Verify lengths
    if len(X_stack_train) != len(train):
        print("Error: Length mismatch between train data and OOF predictions.")
        return

    # 1. Correlation Check
    print("\n--- Correlation Matrix of Base Models (OOF) ---")
    corr_matrix = X_stack_train.corr()
    print(corr_matrix)
    
    if np.any(corr_matrix > 0.98) and np.any(corr_matrix < 1.0):
        print("\nWarning: High correlation detected between some models (> 0.98). Stacking might be less effective.")
    
    # 2. Meta-Model Training (Logistic Regression)
    print("\n--- Training Meta-Learner (Logistic Regression) ---")
    
    kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    meta_model = LogisticRegression(random_state=42)
    
    stack_oof_preds = np.zeros(len(X_stack_train))
    
    for fold, (train_idx, val_idx) in enumerate(kf.split(X_stack_train, y)):
        X_train_fold, X_val_fold = X_stack_train.iloc[train_idx], X_stack_train.iloc[val_idx]
        y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]
        
        meta_model.fit(X_train_fold, y_train_fold)
        stack_oof_preds[val_idx] = meta_model.predict_proba(X_val_fold)[:, 1]
        
    # 3. Output Results
    stacking_auc = roc_auc_score(y, stack_oof_preds)
    print(f"\nStacking OOF AUC Score: {stacking_auc:.5f}")
    
    # Train on full OOF data
    meta_model.fit(X_stack_train, y)
    
    print("\n--- Final Meta-Learner Weights (Coefficients) ---")
    for name, coef in zip(X_stack_train.columns, meta_model.coef_[0]):
        print(f"{name}: {coef:.4f}")
    print(f"Intercept: {meta_model.intercept_[0]:.4f}")
    
    # Save weights
    with open('Models/stacking_weights.txt', 'w') as f:
        f.write(f"Stacking OOF AUC: {stacking_auc:.5f}\n")
        f.write("Weights:\n")
        for name, coef in zip(X_stack_train.columns, meta_model.coef_[0]):
            f.write(f"{name}: {coef:.4f}\n")
        f.write(f"Intercept: {meta_model.intercept_[0]:.4f}\n")
    print("\nWeights saved to Models/stacking_weights.txt")

    # 4. Generate Submission
    if len(subs) == len(OOF_FILES):
        print("\nGenerating submission_stacking.csv...")
        X_stack_test = pd.DataFrame(subs)
        
        # Ensure column order matches training
        X_stack_test = X_stack_test[X_stack_train.columns]
        
        final_preds = meta_model.predict_proba(X_stack_test)[:, 1]
        
        submission = pd.DataFrame({
            'id': test_ids,
            'loan_paid_back': final_preds
        })
        
        submission.to_csv('submission_stacking.csv', index=False)
        print("submission_stacking.csv created successfully!")
    else:
        print("\nSkipping submission generation due to missing submission files for base models.")
        print(f"Found: {list(subs.keys())}")
        print(f"Expected: {list(OOF_FILES.keys())}")

if __name__ == "__main__":
    main()
